### ISSUE TITLE
What's the plan

### ISSUE THREAD

**Issue by jjroley** [wjdoonan/codingstockcenter#1]
So what tech stack are you thinking of?

**Comment by wjdoonan** [comment]
Tech stack?

**Comment by wjdoonan** [comment]
The plan is

> make the front end 

> Make the backend 

> deploy to aws

**Comment by jjroley** [comment]
> Tech stack?

Like React with express, Nextjs, etc

**Comment by wjdoonan** [comment]
Oh I plan to do node

**Comment by jjroley** [comment]
Do you want to use Next.js? It has client and server integrated really well, and it's built around React.

**Comment by wjdoonan** [comment]
Does it integrate with node?

**Comment by jjroley** [comment]
Yes, it's built on node

**Comment by wjdoonan** [comment]
Ok sure that would be great!
